### ISSUE TITLE
Hapus icon pesan 

### ISSUE THREAD

**Issue by dedyrosyadi** [FaruqRahmadani/SI-Lembaga-Kursus-BPC#17]
![image](https://user-images.githubusercontent.com/7915399/46390503-b2e8c600-c70a-11e8-83ba-39fb647d6b00.png)

hapus aja icon ini @FaruqRahmadani

**Comment by FaruqRahmadani** [comment]
siap ka, ulun hapus @dedyrosyadi

**Comment by dedyrosyadi** [comment]
![image](https://user-images.githubusercontent.com/7915399/46390877-a8c7c700-c70c-11e8-8dc1-85d02ba60015.png)
belum ada linknya kah transaksi ini ? @FaruqRahmadani

**Comment by FaruqRahmadani** [comment]
ada ka di pr, blm ulun merge

**Comment by FaruqRahmadani** [comment]
Update di branch #21 commit https://github.com/FaruqRahmadani/SI-Lembaga-Kursus-BPC/pull/21/commits/ee8f857b6335feb7f03a11af5323d75a17ddf38a
