### ISSUE TITLE
Error tambah data program

### ISSUE THREAD

**Issue by dedyrosyadi** [FaruqRahmadani/SI-Lembaga-Kursus-BPC#19]
![image](https://user-images.githubusercontent.com/7915399/46423602-81531780-c769-11e8-8ab0-7c8476b0cb00.png)

@FaruqRahmadani

**Comment by FaruqRahmadani** [comment]
siap ka, ulun cek dulu

**Comment by dedyrosyadi** [comment]
@FaruqRahmadani semalam error pas ku back ku simpan lagi datanya kdpp eh.
