### ISSUE TITLE
Tambah Data Pengajar di Form Program

### ISSUE THREAD

**Issue by dedyrosyadi** [FaruqRahmadani/SI-Lembaga-Kursus-BPC#41]
@FaruqRahmadani 
Tambahkan field nama pengajar di form Program
![image](https://user-images.githubusercontent.com/7915399/48964351-5a35fb00-efe0-11e8-926c-451f5c8de1c1.png)

jadi ketika cetak sertifikat nama untuk ttd sesuai dengan data pengajar
![image](https://user-images.githubusercontent.com/7915399/48964360-7d60aa80-efe0-11e8-8b76-f3ecbd8f1e1c.png)

**Comment by dedyrosyadi** [comment]
@FaruqRahmadani error aku membuka pendaftara  perserta 😆 

![image](https://user-images.githubusercontent.com/7915399/48975322-68e7e500-f0a8-11e8-8be5-27be80d2beb8.png)

**Comment by FaruqRahmadani** [comment]
ulun cek ka 😅

**Comment by dedyrosyadi** [comment]
siap cek aja dulu @FaruqRahmadani

**Comment by FaruqRahmadani** [comment]
sudah dapat ka mslahnya, ulun baiki ka.
td tu ulun sdh kd menuntung akan me isi pendaftaran jdnya error ka 😅

**Comment by dedyrosyadi** [comment]
bujuri akan selajur @FaruqRahmadani 
![image](https://user-images.githubusercontent.com/7915399/48975560-4f499c00-f0ae-11e8-9330-b8168654fd97.png)

**Comment by FaruqRahmadani** [comment]
siap ka, ini lgsng ulun kerjakan ka

**Comment by FaruqRahmadani** [comment]
sudah ulun fix ka @dedyrosyadi

**Comment by dedyrosyadi** [comment]
okesiaap @FaruqRahmadani

**Comment by dedyrosyadi** [comment]
berarti itu sudah kawa otomatis lo nama yg ttd sesuai pengajar ?

**Comment by FaruqRahmadani** [comment]
inggih ka otomatis sdh
